variable = {

    'JPsi_pt' : {
        'var' : 'JPsi_pt',
        'title' : "p^{T}_{#mu#mu} (GeV)",
        'nbins' : 40,
        'min' : 0,
        'max' : 100,
        'logx' : False,
        'logy' : False,
    },
    'JPsi_eta' : {
        'var' : 'JPsi_eta',
        'title' : "#eta_{#mu#mu}",
        'nbins' : 25,
        'min' : -5.,
        'max' : +5.,
        'logx' : False,
        'logy' : False,
    },
    'JPsi_phi' : {
        'var' : 'JPsi_phi',
        'title' : "#varphi_{#mu#mu}",
        'nbins' : 25,
        'min' : -3.1415,
        'max' : +3.1415,
        'logx' : False,
        'logy' : False,
    },
    'JPsi_mass' : {
        'var' : 'JPsi_mass',
        'title' : "m_{#mu#mu} (GeV)",
        'nbins' : 150,
        'min' : 2,
        'max' : 5,
        'logx' : False,
        'logy' : False,
    },
    'JPsi_dEta' : {
        'var' : 'JPsi_dEta',
        'title' : "#Delta #eta_{#mu1,#mu2}",
        'nbins' : 50,
        'min' : 0.,
        'max' : +5.,
        'logx' : False,
        'logy' : False,
    },
    'JPsi_dPhi' : {
        'var' : 'JPsi_dPhi',
        'title' : "#Delta #varphi_{#mu1,#mu2}",
        'nbins' : 60,
        'min' : 0.,
        'max' : +3.1415,
        'logx' : False,
        'logy' : False,
    },
    'JPsi_dR' : {
        'var' : 'JPsi_dR',
        'title' : "#Delta R_{#mu1,#mu2}",
        'nbins' : 50,
        'min' : 0.,
        'max' : 1.,
        'logx' : False,
        'logy' : False,
    },


    'H_pt' : {
        'var' : 'H_pt',
        'title' : "p^{T}_{#mu#mu#gamma} (GeV)",
        'nbins' : 40,
        'min' : 0,
        'max' : 100,
        'logx' : False,
        'logy' : True,
    },
    'H_eta' : {
        'var' : 'H_eta',
        'title' : "#eta_{#mu#mu#gamma}",
        'nbins' : 25,
        'min' : -5.,
        'max' : +5.,
        'logx' : False,
        'logy' : False,
    },
    'H_phi' : {
        'var' : 'H_phi',
        'title' : "#varphi_{#mu#mu#gamma}",
        'nbins' : 25,
        'min' : -3.1415,
        'max' : +3.1415,
        'logx' : False,
        'logy' : False,
    },
    'H_mass' : {
        'var' : 'H_mass',
        'title' : "m_{#mu#mu#gamma} (GeV)",
        'nbins' : 100,
        'min' : 40,
        'max' : 240,
        'logx' : False,
        'logy' : False,
    },
    'H_dEta' : {
        'var' : 'H_dEta',
        'title' : "#Delta #eta_{J/#Psi,#gamma}",
        'nbins' : 50,
        'min' : 0.,
        'max' : +5.,
        'logx' : False,
        'logy' : False,
    },
    'H_dPhi' : {
        'var' : 'H_dPhi',
        'title' : "#Delta #varphi_{J/#Psi,#gamma}",
        'nbins' : 60,
        'min' : 0.,
        'max' : +3.1415,
        'logx' : False,
        'logy' : False,
    },
    'H_dR' : {
        'var' : 'H_dR',
        'title' : "#Delta R_{J/#Psi,#gamma}",
        'nbins' : 25,
        'min' : 0.,
        'max' : 5.,
        'logx' : False,
        'logy' : False,
    },

    'Muon_pt[0]' : {
        'var' : 'Muon_pt[0]',
        'title' : "Muon 1 p_{T} (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 200,
        'logx' : False,
        'logy' : True,
    },
    'Muon_pt[1]' : {
        'var' : 'Muon_pt[1]',
        'title' : "Muon 2 p_{T} (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 100,
        'logx' : False,
        'logy' : True,
    },
#    'Muon_pt[2]' : {
#        'var' : 'Muon_pt[2]',
#        'title' : "Muon 3 p_{T} (GeV)",
#        'nbins' : 40,
#        'min' : 0,
#        'max' : 400,
#        'logx' : False,
#        'logy' : True,
#    },
    'Muon_pfRelIso03_all[0]' : {
        'var' : 'Muon_pfRelIso03_all[0]',
        'title' : "Muon 1 isolation",
        'nbins' : 50,
        'min' : 0,
        'max' : 0.15,
        'logx' : False,
        'logy' : True,
    },
    'Muon_pfRelIso03_all[1]' : {
        'var' : 'Muon_pfRelIso03_all[1]',
        'title' : "Muon 2 isolation",
        'nbins' : 50,
        'min' : 0,
        'max' : 0.15,
        'logx' : False,
        'logy' : True,
    },
#    'Muon_pfRelIso03_all[2]' : {
#        'var' : 'Muon_pfRelIso03_all[2]',
#        'title' : "Muon 3 isolation",
#        'nbins' : 50,
#        'min' : 0,
#        'max' : 1,
#        'logx' : False,
#        'logy' : False,
#    },
    'Muon_charge[0]*Muon_charge[1]' : {
        'var' : 'Muon_charge[0]*Muon_charge[1]',
        'title' : "Muon 1 and 2 sign",
        'nbins' : 3,
        'min' : -1.5,
        'max' : 1.5,
        'logx' : False,
        'logy' : False,
    },
    'Muon_dxy[0]-Muon_dxy[1]' : {
        'var' : 'Muon_dxy[0]-Muon_dxy[1]',
        'title' : "#Delta dxy (#mu1,#mu2)",
        'nbins' : 100,
        'min' : -0.2,
        'max' : 0.2,
        'logx' : False,
        'logy' : True,
    },
    'Muon_dz[0]-Muon_dz[1]' : {
        'var' : 'Muon_dz[0]-Muon_dz[1]',
        'title' : "#Delta dz (#mu1,#mu2)",
        'nbins' : 100,
        'min' : -0.2,
        'max' : 0.2,
        'logx' : False,
        'logy' : True,
    },
#    'Electron_pt[0]' : {
#        'var' : 'Electron_pt[0]',
#        'title' : "Electron 1 p_{T} (GeV)",
#        'nbins' : 80,
#        'min' : 0,
#        'max' : 800,
#        'logx' : False,
#        'logy' : True,
#    },
#    'Electron_pt[1]' : {
#        'var' : 'Electron_pt[1]',
#        'title' : "Electron 2 p_{T} (GeV)",
#        'nbins' : 40,
#        'min' : 0,
#        'max' : 400,
#        'logx' : False,
#        'logy' : True,
#    },
#    'Electron_pt[2]' : {
#        'var' : 'Electron_pt[2]',
#        'title' : "Electron 3 p_{T} (GeV)",
#        'nbins' : 40,
#        'min' : 0,
#        'max' : 400,
#        'logx' : False,
#        'logy' : True,
#    },
#    'Electron_pfRelIso03_all[0]' : {
#        'var' : 'Electron_pfRelIso03_all[0]',
#        'title' : "Electron 1 isolation",
#        'nbins' : 50,
#        'min' : 0,
#        'max' : 1,
#        'logx' : False,
#        'logy' : False,
#    },
#    'Electron_pfRelIso03_all[1]' : {
#        'var' : 'Electron_pfRelIso03_all[1]',
#        'title' : "Electron 2 isolation",
#        'nbins' : 50,
#        'min' : 0,
#        'max' : 1,
#        'logx' : False,
#        'logy' : False,
#    },
#    'Electron_pfRelIso03_all[2]' : {
#        'var' : 'Electron_pfRelIso03_all[2]',
#        'title' : "Electron 3 isolation",
#        'nbins' : 50,
#        'min' : 0,
#        'max' : 1,
#        'logx' : False,
#        'logy' : False,
#    },
#    'Muon_charge[0]*Electron_charge[0]' : {
#        'var' : 'Muon_charge[0]*Electron_charge[0]',
#        'title' : "Muon 1 and Electron 1 sign",
#        'nbins' : 3,
#        'min' : -1.5,
#        'max' : 1.5,
#        'logx' : False,
#        'logy' : False,
#    },
    'MET_pt[0]' : {
        'var' : 'MET_pt[0]',
        'title' : "CHS #slash{E}_{T} (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 200,
        'logx' : False,
        'logy' : True,
    },
    'minMuonIso' : {
        'var' : 'minMuonIso',
        'title' : "minimum Muon Iso",
        'nbins' : 100,
        'min' : 0.,
        'max' : 0.2,
        'logx' : False,
        'logy' : True,
    },
    'maxMuonIso' : {
        'var' : 'maxMuonIso',
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0.,
        'max' : 1.,
        'logx' : False,
        'logy' : True,
    },
    'minMuonMetDPhi' : {
        'var' : 'minMuonMetDPhi',
        'title' : "min #Delta #varphi (#mu, #slash{E}_{T})",
        'nbins' : 50,
        'min' : 0.,
        'max' : 3.1415,
        'logx' : False,
        'logy' : False,
    },
    'maxMuonMetDPhi' : {
        'var' : 'maxMuonMetDPhi',
        'title' : "max #Delta #varphi (#mu, #slash{E}_{T})",
        'nbins' : 50,
        'min' : 0.,
        'max' : 3.1415,
        'logx' : False,
        'logy' : False,
    },
    'photonMetDPhi' : {
        'var' : 'photonMetDPhi',
        'title' : "#Delta #varphi (#gamma, #slash{E}_{T})",
        'nbins' : 50,
        'min' : 0.,
        'max' : 3.1415,
        'logx' : False,
        'logy' : False,
    },
    'metPlusPhotonDPhi' : {
        'var' : 'metPlusPhotonDPhi',
        'title' : "#Delta #varphi (J/#Psi, #slash{E}_{T}+#gamma)",
        'nbins' : 50,
        'min' : 0.,
        'max' : 3.1415,
        'logx' : False,
        'logy' : False,
    },
    'HT30' : {
        'var' : 'HT30',
        'title' : "HT (GeV)",
        'nbins' : 100,
        'min' : 0.,
        'max' : 1000.,
        'logx' : False,
        'logy' : True,
    },
#    'nj20' : {
#        'var' : 'nj20',
#        'title' : "number of clean jets with p_{T}>20 GeV",
#        'nbins' : 15,
#        'min' : -0.5,
#        'max' : 14.5,
#        'logx' : False,
#        'logy' : True,
#    },
#    'nj30' : {
#        'var' : 'nj30',
#        'title' : "number of clean jets with p_{T}>30 GeV",
#        'nbins' : 15,
#        'min' : -0.5,
#        'max' : 14.5,
#        'logx' : False,
#        'logy' : True,
#    },
#    'nj40' : {
#        'var' : 'nj40',
#        'title' : "number of clean jets with p_{T}>40 GeV",
#        'nbins' : 15,
#        'min' : -0.5,
#        'max' : 14.5,
#        'logx' : False,
#        'logy' : True,
#    },
#    'nBJet' : {
#        'var' : 'nBJet',
#        'title' : "number of b-tagged jets",
#        'nbins' : 6,
#        'min' : -0.5,
#        'max' : 5.5,
#        'logx' : False,
#        'logy' : True,
#    },
    'nCleanElectron' : {
        'var' : 'nCleanElectron',
        'title' : "number of clean electrons",
        'nbins' : 6,
        'min' : -0.5,
        'max' : 5.5,
        'logx' : False,
        'logy' : True,
    },
    'nCleanMuon' : {
        'var' : 'nCleanMuon',
        'title' : "number of clean #mu",
        'nbins' : 6,
        'min' : -0.5,
        'max' : 5.5,
        'logx' : False,
        'logy' : True,
    },
    'nCleanTau' : {
        'var' : 'nCleanTau',
        'title' : "number of clean #tau",
        'nbins' : 6,
        'min' : -0.5,
        'max' : 5.5,
        'logx' : False,
        'logy' : True,
    },
    'nCleanPhoton' : {
        'var' : 'nCleanPhoton',
        'title' : "number of clean #gamma",
        'nbins' : 6,
        'min' : -0.5,
        'max' : 5.5,
        'logx' : False,
        'logy' : True,
    },
    'nCleanJet' : {
        'var' : 'nCleanJet',
        'title' : "number of clean jets",
        'nbins' : 15,
        'min' : -0.5,
        'max' : 14.5,
        'logx' : False,
        'logy' : True,
    },
    'nCleanBTagJet' : {
        'var' : 'nCleanBTagJet',
        'title' : "number of clean b-tagged jets",
        'nbins' : 6,
        'min' : -0.5,
        'max' : 5.5,
        'logx' : False,
        'logy' : True,
    },
    'cosThetaStar' : {
        'var' : 'cosThetaStar',
        'title' : "cos #theta^{*}",
        'nbins' : 100,
        'min' : -1.,
        'max' : 1.,
        'logx' : False,
        'logy' : False,
    },
    'cosTheta1' : {
        'var' : 'cosTheta1',
        'title' : "cos #theta_{1}",
        'nbins' : 100,
        'min' : -1.,
        'max' : 1.,
        'logx' : False,
        'logy' : False,
    },
    'phi1' : {
        'var' : 'phi1',
        'title' : "#Phi_{1}",
        'nbins' : 100,
        'min' : -3.1415,
        'max' : 3.1415,
        'logx' : False,
        'logy' : False,
    },
    'Photon_pt[0]' : {
        'var' : 'Photon_pt[0]',
        'title' : "p^{T}_{#gamma} (GeV)",
        'nbins' : 100,
        'min' : 0.,
        'max' : 200.,
        'logx' : False,
        'logy' : True,
    },
    'Photon_eta[0]' : {
        'var' : 'Photon_eta[0]',
        'title' : "#eta_{#gamma}",
        'nbins' : 60,
        'min' : -3.,
        'max' : +3.,
        'logx' : False,
        'logy' : False,
    },
    'Photon_phi[0]' : {
        'var' : 'Photon_phi[0]',
        'title' : "#varphi_{#gamma}",
        'nbins' : 100,
        'min' : -3.1415,
        'max' : +3.1415,
        'logx' : False,
        'logy' : False,
    },
    'Photon_pfRelIso03_all[0]' : {
        'var' : 'Photon_pfRelIso03_all[0]',
        'title' : "#gamma PF isolation",
        'nbins' : 100,
        'min' : 0.,
        'max' : 0.3,
        'logx' : False,
        'logy' : True,
    },
    'Photon_mvaID[0]' : {
        'var' : 'Photon_mvaID[0]',
        'title' : "#gamma mva ID",
        'nbins' : 100,
        'min' : -1,
        'max' : 1.,
        'logx' : False,
        'logy' : True,
    },
    'Photon_eCorr[0]' : {
        'var' : 'Photon_eCorr[0]',
        'title' : "#gamma p_{T} correction",
        'nbins' : 100,
        'min' : 0.9,
        'max' : 1.1,
        'logx' : False,
        'logy' : False,
    },
    'absPhoton_eta' : {
        'var' : 'absPhoton_eta',
        'title' : "|#eta_{#gamma}|",
        'nbins' : 60,
        'min' : -1.5,
        'max' : +3.,
        'logx' : False,
        'logy' : False,
    },
}

