    
variable = {
    'iSkim': {
        'title' : "iSkim",
        'nbins' : 7,
        'min' : -0.5,
        'max' : 6.5,
        'logx' : False,
        'logy' : True,
    },
    'Jpsi_mass': {
        'title' : "m_{ll} (GeV)",
        'nbins' : 100,
        'min' : 1,
        'max' : 4,
        'logx' : False,
        'logy' : False,
    },
    'Jpsi_massPt50': {
        'title' : "m_{ll} (GeV)",
        'nbins' : 100,
        'min' : 1,
        'max' : 4,
        'logx' : False,
        'logy' : False,
    },
    'Jpsi_massHT': {
        'title' : "m_{ll} (GeV)",
        'nbins' : 100,
        'min' : 1,
        'max' : 4,
        'logx' : False,
        'logy' : False,
    },
    'Jpsi_HT': {
        'title' : "m_{ll} (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 2500.,
        'logx' : False,
        'logy' : False,
    },
    'H_mass': {
        'title' : "m_{ll} (GeV)",
        'nbins' : 100,
        'min' : 20,
        'max' : 220,
        'logx' : False,
        'logy' : False,
    },                    
    'Z_mass': {
        'title' : "m_{ll} (GeV)",
        'nbins' : 100,
        'min' : 15,
        'max' : 165,
        'logx' : False,
        'logy' : False,
    },
    'Z_pt': {
        'title' : "p_{T}^{ll} (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 1000,
        'logx' : False,
        'logy' : True,
    },
    'Z_Muonpt1': {
        'title' : "Muon 1 p_{T} (GeV)",
        'nbins' : 80,
        'min' : 0,
        'max' : 800,
        'logx' : False,
        'logy' : True,
    },
    'Z_HT': {
        'title' : "HT (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 2000,
        'logx' : False,
        'logy' : True,
    },  
    'ZW_MTWmmm': {
        'title' : "MTW (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 500,
        'logx' : False,
        'logy' : True,
    }, 
    'ZW_MTWmme': {
        'title' : "MTW (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 500,
        'logx' : False,
        'logy' : True,
    },        
    'ZW_MTWeem': {
        'title' : "MTW (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 500,
        'logx' : False,
        'logy' : True,
    },
    'ZW_M2mu': {
        'title' : "M(mu+mu-) (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 300,
        'logx' : False,
        'logy' : True,
    },           
    'ZW_M2e': {
        'title' : "M(e+e-) (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 300,
        'logx' : False,
        'logy' : True,
    },   
    'ZW_Mmm3mu': {
        'title' : "M(mu+mu-) (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 500,
        'logx' : False,
        'logy' : True,
    },
    'ZW_Mmm2me': {
        'title' : "M(mu+mu-) (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 300,
        'logx' : False,
        'logy' : True,
    },
    'ZW_Mee2em': {
        'title' : "M(mu+mu-) (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 300,
        'logx' : False,
        'logy' : True,
    },
    'ZW_nj30': {
        'title' : "Njets",
        'nbins' : 20,
        'min' : 0,
        'max' : 20,
        'logx' : False,
        'logy' : False,
    },
    'ZW_HT': {
        'title' : "HT",
        'nbins' : 100,
        'min' : 0,
        'max' : 2000.,
        'logx' : False,
        'logy' : False,	
    },
    'mu3_maxMuIso': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,
    },    
    'mu3_HT': {
        'title' : "HT",
        'nbins' : 100,
        'min' : 0,
        'max' : 2000.,
        'logx' : False,
        'logy' : False,	
    },
    'mu3_mMin': {
        'title' : "Mmin",
        'nbins' : 100,
        'min' : 0,
        'max' : 200.,
        'logx' : False,
        'logy' : False,	
    },    
    'mu3_CSVmax': {
        'title' : "CSV",
        'nbins' : 50,
        'min' : 0.,
        'max' : 1.,
        'logx' : False,
        'logy' : False,	
    },
    'mu3_maxMuIsoCSV': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,
    },	
    'mu3_maxMuIsoCSVpt25': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,
    },	
    'mu3_maxMuIsoCSVpt40': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,
    },	     
    'Mue_mass': {
        'title' : "m_{ll} (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 500,
        'logx' : False,
        'logy' : False,
    },
    'Mue_HT': {
        'title' : "HT (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 2000,
        'logx' : False,
        'logy' : False,
    },
    'Mue_nj30': {
        'title' : "Njets",
        'nbins' : 20,
        'min' : 0,
        'max' : 20,
        'logx' : False,
        'logy' : False,
    },
     'Mue_CSVmax': {
        'title' : "CSV",
        'nbins' : 50,
        'min' : 0,
        'max' : 1,
        'logx' : False,
        'logy' : False,
    },
    'e2mu_maxMuIso': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },          
    'e2mu_HT': {
        'title' : "HT",
        'nbins' : 100,
        'min' : 0,
        'max' : 2000.,
        'logx' : False,
        'logy' : False,	
    }, 
    'e2mu_mMin': {
        'title' : "Mmin",
        'nbins' : 100,
        'min' : 0,
        'max' : 200.,
        'logx' : False,
        'logy' : False,	
    },     
    'e2mu_CSVmax': {
        'title' : "CSV",
        'nbins' : 50,
        'min' : 0.,
        'max' : 1.,
        'logx' : False,
        'logy' : False,	
    },          
    'e2mu_maxMuIsoCSV': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },
    'e2mu_maxMuIsoCSVpt25': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },
    'e2mu_maxMuIsoCSVpt40': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },   
    'SSmu_maxMuIso': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    }, 
    'SSmu_maxMuIsoIPlow': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    }, 
    'SSmu_nj30': {
        'title' : "HT",
        'nbins' : 20,
        'min' : 0,
        'max' : 20.,
        'logx' : False,
        'logy' : False,	
    },          
    'SSmu_HT': {
        'title' : "HT",
        'nbins' : 100,
        'min' : 0,
        'max' : 2000.,
        'logx' : False,
        'logy' : False,	
    }, 
    'SSmu_CSVmax': {
        'title' : "HT",
        'nbins' : 50,
        'min' : 0,
        'max' : 1.,
        'logx' : False,
        'logy' : False,	
    },     
    'SSmu_maxMuIso2j': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    }, 
    'SSmu_maxMuIsoHT200': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },     
    'SSmu_maxMuIso2jPt1525': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    }, 
    'SSmu_maxMuIso2jPt2540': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    }, 
    'SSmu_maxMuIso2jPt25': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },   
    'SSmu_maxMuIso2jPt40': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },                        
    'SSmu_maxMuIso2jbveto': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },   
    'SSmu_maxMuIso2jbtag': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    }, 
    'SSmu_maxMuIso2jbtagPt40': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },
    'Z_mass': {
        'title' : "m_{ll} (GeV)",
        'nbins' : 100,
        'min' : 15,
        'max' : 185,
        'logx' : False,
        'logy' : True,
    },
    'Z_pt': {
        'title' : "p_{T}^{ll} (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 1000,
        'logx' : False,
        'logy' : True,
    },
    'W_mass': {
        'title' : "m_{l#nu} (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 200,
        'logx' : False,
        'logy' : False,
    },
    'W_tmass': {
        'title' : "m_{T} (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 200,
        'logx' : False,
        'logy' : False,
    },
    'W_pt': {
        'title' : "p_{T}^{l#nu} (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 1000,
        'logx' : False,
        'logy' : True,
    },
    'Muon_pt[0]': {
        'title' : "Muon 1 p_{T} (GeV)",
        'nbins' : 80,
        'min' : 0,
        'max' : 800,
        'logx' : False,
        'logy' : True,
    },
    'Muon_pt[1]': {
        'title' : "Muon 2 p_{T} (GeV)",
        'nbins' : 40,
        'min' : 0,
        'max' : 400,
        'logx' : False,
        'logy' : True,
    },
    'Muon_pt[2]': {
        'title' : "Muon 3 p_{T} (GeV)",
        'nbins' : 40,
        'min' : 0,
        'max' : 400,
        'logx' : False,
        'logy' : True,
    },
    'Muon_pfRelIso03_all[0]': {
        'title' : "Muon 1 isolation",
        'nbins' : 50,
        'min' : 0,
        'max' : 1,
        'logx' : False,
        'logy' : False,
    },
    'Muon_pfRelIso03_all[1]': {
        'title' : "Muon 2 isolation",
        'nbins' : 50,
        'min' : 0,
        'max' : 1,
        'logx' : False,
        'logy' : False,
    },
    'Muon_pfRelIso03_all[2]': {
        'title' : "Muon 3 isolation",
        'nbins' : 50,
        'min' : 0,
        'max' : 1,
        'logx' : False,
        'logy' : False,
    },
    'Muon_charge[0]*Muon_charge[1]': {
        'title' : "Muon 1 and 2 sign",
        'nbins' : 3,
        'min' : -1.5,
        'max' : 1.5,
        'logx' : False,
        'logy' : False,
    },
    'Electron_pt[0]': {
        'title' : "Electron 1 p_{T} (GeV)",
        'nbins' : 80,
        'min' : 0,
        'max' : 800,
        'logx' : False,
        'logy' : True,
    },
    'Electron_pt[1]': {
        'title' : "Electron 2 p_{T} (GeV)",
        'nbins' : 40,
        'min' : 0,
        'max' : 400,
        'logx' : False,
        'logy' : True,
    },
    'Electron_pt[2]': {
        'title' : "Electron 3 p_{T} (GeV)",
        'nbins' : 40,
        'min' : 0,
        'max' : 400,
        'logx' : False,
        'logy' : True,
    },
    'Electron_pfRelIso03_all[0]': {
        'title' : "Electron 1 isolation",
        'nbins' : 50,
        'min' : 0,
        'max' : 1,
        'logx' : False,
        'logy' : False,
    },
    'Electron_pfRelIso03_all[1]': {
        'title' : "Electron 2 isolation",
        'nbins' : 50,
        'min' : 0,
        'max' : 1,
        'logx' : False,
        'logy' : False,
    },
    'Electron_pfRelIso03_all[2]': {
        'title' : "Electron 3 isolation",
        'nbins' : 50,
        'min' : 0,
        'max' : 1,
        'logx' : False,
        'logy' : False,
    },
    'Muon_charge[0]*Electron_charge[0]': {
        'title' : "Muon 1 and Electron 1 sign",
        'nbins' : 3,
        'min' : -1.5,
        'max' : 1.5,
        'logx' : False,
        'logy' : False,
    },
    'minMuonIso': {
        'title' : "minimum Muon Iso",
        'nbins' : 100,
        'min' : 0.01,
        'max' : 5.01,
        'logx' : True,
        'logy' : False,
    },
    'maxMuonIso': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0.01,
        'max' : 5.01,
        'logx' : True,
        'logy' : False,
    },
    'lumiWeight': {
        'title' : "lumiWeight",
        'nbins' : 1000,
        'min' : 0.,
        'max' : 1.5,
        'logx' : False,
        'logy' : True,
    },
}

