variable = {
    'iSkim' : {
        'title' : "iSkim",
        'nbins' : 7,
        'min' : -0.5,
        'max' : 6.5,
        'logx' : False,
        'logy' : True,
    },
    'Jpsi_mass' : {
        'title' : "m_{ll} (GeV)",
        'nbins' : 100,
        'min' : 1,
        'max' : 4,
        'logx' : False,
        'logy' : False,
    },
    'Jpsi_massPt50' : {
        'title' : "m_{ll} (GeV)",
        'nbins' : 100,
        'min' : 1,
        'max' : 4,
        'logx' : False,
        'logy' : False,
    },
    'Jpsi_massHT' : {
        'title' : "m_{ll} (GeV)",
        'nbins' : 100,
        'min' : 1,
        'max' : 4,
        'logx' : False,
        'logy' : False,
    },
    'Jpsi_HT' : {
        'title' : "m_{ll} (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 2500.,
        'logx' : False,
        'logy' : False,
    },
    'Jpsi_dxy' : {
        'title' : "dxy (cm)",
        'nbins' : 100,
        'min' : 0,
        'max' : 0.2,
        'logx' : False,
        'logy' : False,
    },    
    'H_M4mu' : {
        'title' : "m_{ll} (GeV)",
        'nbins' : 100,
        'min' : 40,
        'max' : 240,
        'logx' : False,
        'logy' : False,
    }, 
    'H_M2mu2e' : {
        'title' : "m_{ll} (GeV)",
        'nbins' : 100,
        'min' : 40,
        'max' : 240,
        'logx' : False,
        'logy' : False,
    }, 
    'H_M4e' : {
        'title' : "m_{ll} (GeV)",
        'nbins' : 100,
        'min' : 40,
        'max' : 240,
        'logx' : False,
        'logy' : False,
    },  
    'H_M4lept' : {
        'title' : "m_{4l} (GeV)",
        'nbins' : 100,
        'min' : 40,
        'max' : 340,
        'logx' : False,
        'logy' : False,
    },                                
    'Z_mm' : {
        'title' : "m_{ll} (GeV)",
        'nbins' : 100,
        'min' : 15,
        'max' : 165,
        'logx' : False,
        'logy' : False,
    },
    'Z_pt' : {
        'title' : "p_{T}^{ll} (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 1000,
        'logx' : False,
        'logy' : True,
    },
    'Z_Muonpt1' : {
        'title' : "Muon 1 p_{T} (GeV)",
        'nbins' : 80,
        'min' : 0,
        'max' : 800,
        'logx' : False,
        'logy' : True,
    },
    'Z_HT' : {
        'title' : "HT (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 2000,
        'logx' : False,
        'logy' : True,
    }, 
    'Z_ee' : {
        'title' : "m_{ll} (GeV)",
        'nbins' : 100,
        'min' : 15,
        'max' : 165,
        'logx' : False,
        'logy' : False,
    },
    'Z_ptee' : {
        'title' : "p_{T}^{ll} (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 1000,
        'logx' : False,
        'logy' : True,
    },
    'Z_Electronpt1' : {
        'title' : "Muon 1 p_{T} (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 500,
        'logx' : False,
        'logy' : True,
    },
    'Z_HTee' : {
        'title' : "HT (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 2000,
        'logx' : False,
        'logy' : True,
    },      
    'Z_eebarrel' : {
        'title' : "m_{ll} (GeV)",
        'nbins' : 100,
        'min' : 15,
        'max' : 165,
        'logx' : False,
        'logy' : False,
    },
    'Z_eeendcap' : {
        'title' : "m_{ll} (GeV)",
        'nbins' : 100,
        'min' : 15,
        'max' : 165,
        'logx' : False,
        'logy' : False,
    },
    'Z_eeSSbarrel' : {
        'title' : "m_{ll} (GeV)",
        'nbins' : 100,
        'min' : 15,
        'max' : 165,
        'logx' : False,
        'logy' : False,
    },
    'Z_eeSSendcap' : {
        'title' : "m_{ll} (GeV)",
        'nbins' : 100,
        'min' : 15,
        'max' : 165,
        'logx' : False,
        'logy' : False,
    },        
    'Z_Elept1barrel' : {
        'title' : "Electron 1 p_{T} (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 500,
        'logx' : False,
        'logy' : True,
    },
    'Z_Elept1endcap' : {
        'title' : "Electron 1 p_{T} (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 500,
        'logx' : False,
        'logy' : True,
    },
    'Z_Elept1SSbarrel' : {
        'title' : "Electron 1 p_{T} (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 500,
        'logx' : False,
        'logy' : True,
    },
    'Z_Elept1SSendcap' : {
        'title' : "Electron 1 p_{T} (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 500,
        'logx' : False,
        'logy' : True,
    },     
    'ZW_MTW3lept' : {
        'title' : "MTW (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 500,
        'logx' : False,
        'logy' : True,
    }, 
    'ZW_MTW3leptCSV' : {
        'title' : "MTW (GeV)",
        'nbins' : 30,
        'min' : 0,
        'max' : 300,
        'logx' : False,
        'logy' : True,
    },                
    'ZW_MTWmmm' : {
        'title' : "MTW (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 500,
        'logx' : False,
        'logy' : True,
    }, 
    'ZW_MTWmmmCSV' : {
        'title' : "MTW (GeV)",
        'nbins' : 30,
        'min' : 0,
        'max' : 300,
        'logx' : False,
        'logy' : True,
    },     
    'ZW_MTWmme' : {
        'title' : "MTW (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 500,
        'logx' : False,
        'logy' : True,
    },     
    'ZW_MTWmmeCSV' : {
        'title' : "MTW (GeV)",
        'nbins' : 30,
        'min' : 0,
        'max' : 300,
        'logx' : False,
        'logy' : True,
    },            
    'ZW_MTWeem' : {
        'title' : "MTW (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 500,
        'logx' : False,
        'logy' : True,
    },
    'ZW_MTWeemCSV' : {
        'title' : "MTW (GeV)",
        'nbins' : 30,
        'min' : 0,
        'max' : 300,
        'logx' : False,
        'logy' : True,
    },         
    'ZW_MTWeee' : {
        'title' : "MTW (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 500,
        'logx' : False,
        'logy' : True,
    },      
    'ZW_MTWeeeCSV' : {
        'title' : "MTW (GeV)",
        'nbins' : 30,
        'min' : 0,
        'max' : 300,
        'logx' : False,
        'logy' : True,
    },         
    'ZW_Mmm3mu' : {
        'title' : "M(mu+mu-) (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 300,
        'logx' : False,
        'logy' : True,
    },
    'ZW_Mmm2me' : {
        'title' : "M(mu+mu-) (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 300,
        'logx' : False,
        'logy' : True,
    },
    'ZW_Mee2em' : {
        'title' : "M(e+e-) (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 300,
        'logx' : False,
        'logy' : True,
    },
    'ZW_Mee3e' : {
        'title' : "M(e+e-) (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 300,
        'logx' : False,
        'logy' : True,
    },    
    'ZW_Mmm3muCSV' : {
        'title' : "M(mu+mu-) (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 300,
        'logx' : False,
        'logy' : True,
    },
    'ZW_Mmm2meCSV' : {
        'title' : "M(mu+mu-) (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 300,
        'logx' : False,
        'logy' : True,
    },
    'ZW_Mee2emCSV' : {
        'title' : "M(e+e-) (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 300,
        'logx' : False,
        'logy' : True,
    },
    'ZW_Mee3eCSV' : {
        'title' : "M(e+e-) (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 300,
        'logx' : False,
        'logy' : True,
    },
    'ZW_Mll3leptCSV' : {
        'title' : "M(ll) (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 300,
        'logx' : False,
        'logy' : True,
    },            
    'ZW_MET3mu' : {
        'title' : "MET (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 500,
        'logx' : False,
        'logy' : True,
    },
    'ZW_MET2me' : {
        'title' : "MET (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 500,
        'logx' : False,
        'logy' : True,
    },
    'ZW_MET2em' : {
        'title' : "MET (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 500,
        'logx' : False,
        'logy' : True,
    },
    'ZW_MET3e' : {
        'title' : "MET (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 500,
        'logx' : False,
        'logy' : True,
    },        
    'ZW_nj30' : {
        'title' : "Njets",
        'nbins' : 20,
        'min' : 0,
        'max' : 20,
        'logx' : False,
        'logy' : False,
    },
    'ZW_nj30CSV' : {
        'title' : "Njets",
        'nbins' : 20,
        'min' : 0,
        'max' : 20,
        'logx' : False,
        'logy' : False,
    },    
    'ZW_HT' : {
        'title' : "HT",
        'nbins' : 40,
        'min' : 0,
        'max' : 2000.,
        'logx' : False,
        'logy' : False,	
    },
    'ZW_ptZ' : {
        'title' : "ptZ",
        'nbins' : 40,
        'min' : 0,
        'max' : 1000.,
        'logx' : False,
        'logy' : False,	
    },    
    'ZW_HTCSV' : {
        'title' : "HT",
        'nbins' : 40,
        'min' : 0,
        'max' : 2000.,
        'logx' : False,
        'logy' : False,	
    },	
    'ZW_ptZCSV' : {
        'title' : "ptZ",
        'nbins' : 40,
        'min' : 0,
        'max' : 1000.,
        'logx' : False,
        'logy' : False,	 
    },    
    'ZW_CSV' : {
        'title' : "CSV ",
        'nbins' : 50,
        'min' : 0,
        'max' : 1.,
        'logx' : False,
        'logy' : True,
    }, 
    'ZW_CSV2' : {
        'title' : "CSV ",
        'nbins' : 50,
        'min' : 0,
        'max' : 1.,
        'logx' : False,
        'logy' : True,
    },         
    'mu3_maxMuIso' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,
    },    
    'mu3_HT' : {
        'title' : "HT",
        'nbins' : 100,
        'min' : 0,
        'max' : 2000.,
        'logx' : False,
        'logy' : False,	
    },
    'mu3_mMin' : {
        'title' : "Mmin",
        'nbins' : 100,
        'min' : 0,
        'max' : 200.,
        'logx' : False,
        'logy' : False,	
    },    
    'mu3_CSVmax' : {
        'title' : "CSV",
        'nbins' : 50,
        'min' : 0.,
        'max' : 1.,
        'logx' : False,
        'logy' : False,	
    },
    'mu3_maxMuIsoCSVpt1525' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,
    },	
    'mu3_maxMuIsoCSVpt25' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,
    },	
    'mu3_maxMuIsoCSVpt40' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,
    },
    'Mue_isomu' : {
        'title' : "isomu",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,
    },    	     
    'Mue_mass' : {
        'title' : "m_{ll} (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 500,
        'logx' : False,
        'logy' : False,
    },
    'Mue_HT' : {
        'title' : "HT (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 2000,
        'logx' : False,
        'logy' : False,
    },
    'Mue_nj30' : {
        'title' : "Njets",
        'nbins' : 20,
        'min' : 0,
        'max' : 20,
        'logx' : False,
        'logy' : False,
    },
     'Mue_CSVmax' : {
        'title' : "CSV",
        'nbins' : 50,
        'min' : 0,
        'max' : 1,
        'logx' : False,
        'logy' : False,
    },
    'e2mu_maxMuIso' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },          
    'e2mu_HT' : {
        'title' : "HT",
        'nbins' : 100,
        'min' : 0,
        'max' : 2000.,
        'logx' : False,
        'logy' : False,	
    }, 
    'e2mu_mMin' : {
        'title' : "Mmin",
        'nbins' : 100,
        'min' : 0,
        'max' : 200.,
        'logx' : False,
        'logy' : False,	
    },     
    'e2mu_CSVmax' : {
        'title' : "CSV",
        'nbins' : 50,
        'min' : 0.,
        'max' : 1.,
        'logx' : False,
        'logy' : False,	
    },          
    'e2mu_maxMuIsoCSVpt1525' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },
    'e2mu_maxMuIsoCSVpt25' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },
    'e2mu_maxMuIsoCSVpt40' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },
    'lept3_maxMuIsoCSVpt1525' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,
    },	
    'lept3_maxMuIsoCSVpt25' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,
    },	
    'lept3_maxMuIsoCSVpt40' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,
    },       
    'SSmu_maxMuIso' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    }, 
    'SSmu_maxMuIsoIPlow' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    }, 
    'SSmu_nj30' : {
        'title' : "HT",
        'nbins' : 20,
        'min' : 0,
        'max' : 20.,
        'logx' : False,
        'logy' : False,	
    },          
    'SSmu_HT' : {
        'title' : "HT",
        'nbins' : 100,
        'min' : 0,
        'max' : 2000.,
        'logx' : False,
        'logy' : False,	
    }, 
    'SSmu_CSVmax' : {
        'title' : "CSVmax",
        'nbins' : 50,
        'min' : 0,
        'max' : 1.,
        'logx' : False,
        'logy' : False,	
    },  
    'SSmu_CSVmaxLowIso' : {
        'title' : "CSVmax",
        'nbins' : 20,
        'min' : 0,
        'max' : 1.,
        'logx' : False,
        'logy' : False,	
    },         
    'SSmu_maxMuIso2j' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    }, 
    'SSmu_maxMuIsoHT200' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },     
    'SSmu_maxMuIso2jPt1525' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    }, 
    'SSmu_maxMuIso2jPt2540' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    }, 
    'SSmu_maxMuIso2jPt25' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },   
    'SSmu_maxMuIso2jPt40' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },                        
    'SSmu_maxMuIso2jPt1525higIP' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    }, 
    'SSmu_maxMuIso2jPt2540higIP' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    }, 
    'SSmu_maxMuIso2jPt25higIP' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },   
    'SSmu_maxMuIso2jPt40higIP' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },  
    'SSmu_maxMuIso2jbveto' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },
   'SSmu_maxMuIsobvetoplus' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },
   'SSmu_maxMuIsobvetominus' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },         
    'SSmu_maxMuIso2jbvetoPt1525' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },
    'SSmu_Mjjbveto' : {
        'title' : "Mjj (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 2500.,
        'logx' : False,
        'logy' : False,	
    },     
    'SSmu_Mjjbvetoplus' : {
        'title' : "Mjj (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 2500.,
        'logx' : False,
        'logy' : False,	
    },
    'SSmu_Mjjbvetominus' : {
        'title' : "Mjj (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 2500.,
        'logx' : False,
        'logy' : False,	
    },               
    'SSmu_maxMuIso2jbtag' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },
    'SSmu_maxMuIso2jbtagPt1525' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },     
    'SSmu_maxMuIso2jbtagPt40' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },
    'SSmu_maxMuIso2jbtagHT350' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },     
    'SSmu_HTbtagPt25' : {
        'title' : "HT",
        'nbins' : 40,
        'min' : 0,
        'max' : 2000.,
        'logx' : False,
        'logy' : False,	
    },    
    'SSmue_maxMuIso' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    }, 
    'SSmue_maxMuIsoIPlow' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    }, 
    'SSmue_maxMuIsoTRGele' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },     
    'SSmue_nj30' : {
        'title' : "HT",
        'nbins' : 20,
        'min' : 0,
        'max' : 20.,
        'logx' : False,
        'logy' : False,	
    },          
    'SSmue_HT' : {
        'title' : "HT",
        'nbins' : 100,
        'min' : 0,
        'max' : 2000.,
        'logx' : False,
        'logy' : False,	
    }, 
    'SSmue_CSVmax' : {
        'title' : "CSVmax",
        'nbins' : 50,
        'min' : 0,
        'max' : 1.,
        'logx' : False,
        'logy' : False,	
    },  
    'SSmue_CSVmaxLowIso' : {
        'title' : "CSVmax",
        'nbins' : 20,
        'min' : 0,
        'max' : 1.,
        'logx' : False,
        'logy' : False,	
    },         
    'SSmue_maxMuIso2j' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    }, 
    'SSmue_maxMuIsoHT200' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },     
    'SSmue_maxMuIso2jPt1525' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    }, 
    'SSmue_maxMuIso2jPt2540' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    }, 
    'SSmue_maxMuIso2jPt25' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },   
    'SSmue_maxMuIso2jPt40' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },                        
    'SSmue_maxMuIso2jbveto' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },
   'SSmue_maxMuIsobvetoplus' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },
   'SSmue_maxMuIsobvetominus' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },         
    'SSmue_maxMuIso2jbvetoPt1525' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },
    'SSmue_Mjjbveto' : {
        'title' : "Mjj (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 2500.,
        'logx' : False,
        'logy' : False,	
    },     
    'SSmue_Mjjbvetoplus' : {
        'title' : "Mjj (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 2500.,
        'logx' : False,
        'logy' : False,	
    },
    'SSmue_Mjjbvetominus' : {
        'title' : "Mjj (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 2500.,
        'logx' : False,
        'logy' : False,	
    },               
    'SSmue_maxMuIso2jbtag' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },
    'SSmue_maxMuIso2jbtagPt1525' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },     
    'SSmue_maxMuIso2jbtagPt40' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },
    'SSmue_maxMuIso2jbtagHT350' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },    
    'SSmue_HTbtagPt25' : {
        'title' : "HT",
        'nbins' : 40,
        'min' : 0,
        'max' : 2000.,
        'logx' : False,
        'logy' : False,	
    },     
    'tt_Wqqmass' : {
        'title' : "Mjj (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 1000,
        'logx' : False,
        'logy' : False,
    },  
    'tt_Tlvb1' : {
        'title' : "Mlvb1 (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 1000,
        'logx' : False,
        'logy' : False,
    },  
    'tt_Tlvb2' : {
        'title' : "Mlvb2 (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 1000,
        'logx' : False,
        'logy' : False,
    },  
    'tt_Tqqb1' : {
        'title' : "Mqqb1 (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 1000,
        'logx' : False,
        'logy' : False,
    },  
    'tt_Tqqb2' : {
        'title' : "Mqqb2 (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 1000,
        'logx' : False,
        'logy' : False,
    },                   
    'tte_Wqqmass' : {
        'title' : "Mjj (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 1000,
        'logx' : False,
        'logy' : False,
    },  
    'tte_Tlvb1' : {
        'title' : "Mlvb1 (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 1000,
        'logx' : False,
        'logy' : False,
    },  
    'tte_Tlvb2' : {
        'title' : "Mlvb2 (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 1000,
        'logx' : False,
        'logy' : False,
    },  
    'tte_Tqqb1' : {
        'title' : "Mqqb1 (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 1000,
        'logx' : False,
        'logy' : False,
    },  
    'tte_Tqqb2' : {
        'title' : "Mqqb2 (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 1000,
        'logx' : False,
        'logy' : False,
    },                        
    'W_mass' : {
        'title' : "m_{l#nu} (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 200,
        'logx' : False,
        'logy' : False,
    },
    'W_tmass' : {
        'title' : "m_{T} (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 400,
        'logx' : False,
        'logy' : False,
    },
    'W_pt' : {
        'title' : "p_{T}^{l#nu} (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 1000,
        'logx' : False,
        'logy' : True,
    },
    'Muon_pt[0]' : {
        'title' : "Muon 1 p_{T} (GeV)",
        'nbins' : 80,
        'min' : 0,
        'max' : 800,
        'logx' : False,
        'logy' : True,
    },
    'Muon_pt[1]' : {
        'title' : "Muon 2 p_{T} (GeV)",
        'nbins' : 40,
        'min' : 0,
        'max' : 400,
        'logx' : False,
        'logy' : True,
    },
    'Muon_pt[2]' : {
        'title' : "Muon 3 p_{T} (GeV)",
        'nbins' : 40,
        'min' : 0,
        'max' : 400,
        'logx' : False,
        'logy' : True,
    },
    'Muon_pfRelIso03_all[0]' : {
        'title' : "Muon 1 isolation",
        'nbins' : 50,
        'min' : 0,
        'max' : 1,
        'logx' : False,
        'logy' : False,
    },
    'Muon_pfRelIso03_all[1]' : {
        'title' : "Muon 2 isolation",
        'nbins' : 50,
        'min' : 0,
        'max' : 1,
        'logx' : False,
        'logy' : False,
    },
    'Muon_pfRelIso03_all[2]' : {
        'title' : "Muon 3 isolation",
        'nbins' : 50,
        'min' : 0,
        'max' : 1,
        'logx' : False,
        'logy' : False,
    },
    'Muon_charge[0]*Muon_charge[1]' : {
        'title' : "Muon 1 and 2 sign",
        'nbins' : 3,
        'min' : -1.5,
        'max' : 1.5,
        'logx' : False,
        'logy' : False,
    },
    'Electron_pt[0]' : {
        'title' : "Electron 1 p_{T} (GeV)",
        'nbins' : 80,
        'min' : 0,
        'max' : 800,
        'logx' : False,
        'logy' : True,
    },
    'Electron_pt[1]' : {
        'title' : "Electron 2 p_{T} (GeV)",
        'nbins' : 40,
        'min' : 0,
        'max' : 400,
        'logx' : False,
        'logy' : True,
    },
    'Electron_pt[2]' : {
        'title' : "Electron 3 p_{T} (GeV)",
        'nbins' : 40,
        'min' : 0,
        'max' : 400,
        'logx' : False,
        'logy' : True,
    },
    'Electron_pfRelIso03_all[0]' : {
        'title' : "Electron 1 isolation",
        'nbins' : 50,
        'min' : 0,
        'max' : 1,
        'logx' : False,
        'logy' : False,
    },
    'Electron_pfRelIso03_all[1]' : {
        'title' : "Electron 2 isolation",
        'nbins' : 50,
        'min' : 0,
        'max' : 1,
        'logx' : False,
        'logy' : False,
    },
    'Electron_pfRelIso03_all[2]' : {
        'title' : "Electron 3 isolation",
        'nbins' : 50,
        'min' : 0,
        'max' : 1,
        'logx' : False,
        'logy' : False,
    },
    'Muon_charge[0]*Electron_charge[0]' : {
        'title' : "Muon 1 and Electron 1 sign",
        'nbins' : 3,
        'min' : -1.5,
        'max' : 1.5,
        'logx' : False,
        'logy' : False,
    },
    'MET_pt[0]' : {
        'title' : "CHS #slash{E}_{T} (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 400,
        'logx' : False,
        'logy' : True,
    },
    'minMuonIso' : {
        'title' : "minimum Muon Iso",
        'nbins' : 100,
        'min' : 0.01,
        'max' : 5.01,
        'logx' : False,
        'logy' : True,
    },
    'maxMuonIso' : {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0.01,
        'max' : 5.01,
        'logx' : False,
        'logy' : True,
    },
    'minMuonMetDPhi' : {
        'title' : "min #Delta #phi (#mu, #slash{E}_{T})",
        'nbins' : 50,
        'min' : 0.,
        'max' : 3.1415,
        'logx' : False,
        'logy' : False,
    },
    'maxMuonMetDPhi' : {
        'title' : "max #Delta #phi (#mu, #slash{E}_{T})",
        'nbins' : 50,
        'min' : 0.,
        'max' : 3.1415,
        'logx' : False,
        'logy' : False,
    },
    'minMuonJetDR' : {
        'title' : "min #Delta R (#mu, j)",
        'nbins' : 50,
        'min' : 0.,
        'max' : 5.,
        'logx' : False,
        'logy' : False,
    },
    'HT30' : {
        'title' : "HT (GeV)",
        'nbins' : 100,
        'min' : 0.,
        'max' : 1000.,
        'logx' : False,
        'logy' : True,
    },
    'nj20' : {
        'title' : "number of clean jets with p_{T}>20 GeV",
        'nbins' : 15,
        'min' : -0.5,
        'max' : 14.5,
        'logx' : False,
        'logy' : True,
    },
    'nj30' : {
        'title' : "number of clean jets with p_{T}>30 GeV",
        'nbins' : 15,
        'min' : -0.5,
        'max' : 14.5,
        'logx' : False,
        'logy' : True,
    },
    'nj40' : {
        'title' : "number of clean jets with p_{T}>40 GeV",
        'nbins' : 15,
        'min' : -0.5,
        'max' : 14.5,
        'logx' : False,
        'logy' : True,
    },
    'nBJet' : {
        'title' : "number of b-tagged jets",
        'nbins' : 6,
        'min' : -0.5,
        'max' : 5.5,
        'logx' : False,
        'logy' : True,
    },
    'nCleanElectron' : {
        'title' : "number of clean electrons",
        'nbins' : 6,
        'min' : -0.5,
        'max' : 5.5,
        'logx' : False,
        'logy' : True,
    },
    'nCleanMuon' : {
        'title' : "number of clean muons",
        'nbins' : 6,
        'min' : -0.5,
        'max' : 5.5,
        'logx' : False,
        'logy' : True,
    },
    'nCleanJet' : {
        'title' : "number of clean jets",
        'nbins' : 15,
        'min' : -0.5,
        'max' : 14.5,
        'logx' : False,
        'logy' : True,
    },
    'll_dEta' : {
        'title' : "#Delta #eta (ll)",
        'nbins' : 100,
        'min' : 0.,
        'max' : 5.,
        'logx' : False,
        'logy' : False,
    },
    'll_dPhi' : {
        'title' : "#Delta #phi (ll)",
        'nbins' : 100,
        'min' : 0.,
        'max' : 3.1415,
        'logx' : False,
        'logy' : False,
    },
    'll_dR' : {
        'title' : "#Delta R (ll)",
        'nbins' : 100,
        'min' : 0.,
        'max' : 5.,
        'logx' : False,
        'logy' : False,
    },
    'Wqq_mass' : {
        'title' : "hadronic W mass (GeV)",
        'nbins' : 100,
        'min' : 0.,
        'max' : 200.,
        'logx' : False,
        'logy' : False,
    },
    'Tlvb1_mass' : {
        'title' : "leptonic top 1 mass (GeV)",
        'nbins' : 100,
        'min' : 0.,
        'max' : 400.,
        'logx' : False,
        'logy' : False,
    },
    'Tlvb2_mass' : {
        'title' : "leptonic top 2 mass (GeV)",
        'nbins' : 100,
        'min' : 0.,
        'max' : 400.,
        'logx' : False,
        'logy' : False,
    },
    'Tqqb1_mass' : {
        'title' : "hadronic top 1 mass (GeV)",
        'nbins' : 100,
        'min' : 0.,
        'max' : 400.,
        'logx' : False,
        'logy' : False,
    },
    'Tqqb2_mass' : {
        'title' : "hadronic top 2 mass (GeV)",
        'nbins' : 100,
        'min' : 0.,
        'max' : 400.,
        'logx' : False,
        'logy' : False,
    },
    'jj_mass' : {
        'title' : "m_{jj} (GeV)",
        'nbins' : 100,
        'min' : 0.,
        'max' : 400,
        'logx' : False,
        'logy' : False,
    },
    'jj_pt' : {
        'title' : "p_{T}^{jj} (GeV)",
        'nbins' : 100,
        'min' : 0.,
        'max' : 200.,
        'logx' : False,
        'logy' : True,
    },
    'jj_dEta' : {
        'title' : "#Delta #eta (jj)",
        'nbins' : 100,
        'min' : 0.,
        'max' : 3.1415,
        'logx' : False,
        'logy' : False,
    },
    'jj_dPhi' : {
        'title' : "#Delta #phi (jj)",
        'nbins' : 100,
        'min' : 0.,
        'max' : 5.,
        'logx' : False,
        'logy' : False,
    },
    'jj_dR' : {
        'title' : "#Delta R (jj)",
        'nbins' : 100,
        'min' : 0.,
        'max' : 5.,
        'logx' : False,
        'logy' : False,
    },
    'nj_mass' : {
        'title' : "m_{all jets} (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 400,
        'logx' : False,
        'logy' : False,
    },
    'vis_mass' : {
        'title' : "m_{all} (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 400,
        'logx' : False,
        'logy' : False,
    },
    'lljj_mass' : {
        'title' : "m_{lljj} (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 400,
        'logx' : False,
        'logy' : False,
    },
    'lumiWeight' : {
        'title' : "lumiWeight",
        'nbins' : 1000,
        'min' : 0.,
        'max' : 1.5,
        'logx' : False,
        'logy' : True,
    },
}

