variable = {
    'iSkim': {
        'title' : "iSkim",
        'nbins' : 7,
        'min' : -0.5,
        'max' : 6.5,
        'logx' : False,
        'logy' : True,
    },
    'Jpsi_mass': {
        'title' : "m_{ll} (GeV)",
        'nbins' : 100,
        'min' : 1,
        'max' : 4,
        'logx' : False,
        'logy' : False,
    },
    'Jpsi_massPt50': {
        'title' : "m_{ll} (GeV)",
        'nbins' : 100,
        'min' : 1,
        'max' : 4,
        'logx' : False,
        'logy' : False,
    },
    'Jpsi_massHT': {
        'title' : "m_{ll} (GeV)",
        'nbins' : 100,
        'min' : 1,
        'max' : 4,
        'logx' : False,
        'logy' : False,
    },
    'Jpsi_HT': {
        'title' : "m_{ll} (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 2500.,
        'logx' : False,
        'logy' : False,
    },
    'Jpsi_dxy': {
        'title' : "dxy (cm)",
        'nbins' : 100,
        'min' : 0,
        'max' : 0.2,
        'logx' : False,
        'logy' : False,
    },    
    'H_M4mu': {
        'title' : "m_{ll} (GeV)",
        'nbins' : 100,
        'min' : 40,
        'max' : 240,
        'logx' : False,
        'logy' : False,
    }, 
    'H_M2mu2e': {
        'title' : "m_{ll} (GeV)",
        'nbins' : 100,
        'min' : 40,
        'max' : 240,
        'logx' : False,
        'logy' : False,
    }, 
    'H_M4e': {
        'title' : "m_{ll} (GeV)",
        'nbins' : 100,
        'min' : 40,
        'max' : 240,
        'logx' : False,
        'logy' : False,
    },  
    'H_M4lept': {
        'title' : "m_{4l} (GeV)",
        'nbins' : 100,
        'min' : 40,
        'max' : 340,
        'logx' : False,
        'logy' : False,
    },                                
    'Z_mm': {
        'title' : "m_{ll} (GeV)",
        'nbins' : 100,
        'min' : 15,
        'max' : 165,
        'logx' : False,
        'logy' : False,
    },
    'Z_pt': {
        'title' : "p_{T}^{ll} (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 1000,
        'logx' : False,
        'logy' : True,
    },
    'Z_Muonpt1': {
        'title' : "Muon 1 p_{T} (GeV)",
        'nbins' : 80,
        'min' : 0,
        'max' : 800,
        'logx' : False,
        'logy' : True,
    },
    'Z_HT': {
        'title' : "HT (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 2000,
        'logx' : False,
        'logy' : True,
    }, 
    'Z_ee': {
        'title' : "m_{ll} (GeV)",
        'nbins' : 100,
        'min' : 15,
        'max' : 165,
        'logx' : False,
        'logy' : False,
    },
    'Z_ptee': {
        'title' : "p_{T}^{ll} (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 1000,
        'logx' : False,
        'logy' : True,
    },
    'Z_Electronpt1': {
        'title' : "Muon 1 p_{T} (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 500,
        'logx' : False,
        'logy' : True,
    },
    'Z_HTee': {
        'title' : "HT (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 2000,
        'logx' : False,
        'logy' : True,
    },      
    'Z_eebarrel': {
        'title' : "m_{ll} (GeV)",
        'nbins' : 100,
        'min' : 15,
        'max' : 165,
        'logx' : False,
        'logy' : False,
    },
    'Z_eeendcap': {
        'title' : "m_{ll} (GeV)",
        'nbins' : 100,
        'min' : 15,
        'max' : 165,
        'logx' : False,
        'logy' : False,
    },
    'Z_eeSSbarrel': {
        'title' : "m_{ll} (GeV)",
        'nbins' : 100,
        'min' : 15,
        'max' : 165,
        'logx' : False,
        'logy' : False,
    },
    'Z_eeSSendcap': {
        'title' : "m_{ll} (GeV)",
        'nbins' : 100,
        'min' : 15,
        'max' : 165,
        'logx' : False,
        'logy' : False,
    },        
    'Z_Elept1barrel': {
        'title' : "Electron 1 p_{T} (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 500,
        'logx' : False,
        'logy' : True,
    },
    'Z_Elept1endcap': {
        'title' : "Electron 1 p_{T} (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 500,
        'logx' : False,
        'logy' : True,
    },
    'Z_Elept1SSbarrel': {
        'title' : "Electron 1 p_{T} (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 500,
        'logx' : False,
        'logy' : True,
    },
    'Z_Elept1SSendcap': {
        'title' : "Electron 1 p_{T} (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 500,
        'logx' : False,
        'logy' : True,
    },     
    'ZW_MTW3lept': {
        'title' : "MTW (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 500,
        'logx' : False,
        'logy' : True,
    }, 
    'ZW_MTW3leptCSV': {
        'title' : "MTW (GeV)",
        'nbins' : 30,
        'min' : 0,
        'max' : 300,
        'logx' : False,
        'logy' : True,
    },                
    'ZW_MTWmmm': {
        'title' : "MTW (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 500,
        'logx' : False,
        'logy' : True,
    }, 
    'ZW_MTWmmmCSV': {
        'title' : "MTW (GeV)",
        'nbins' : 30,
        'min' : 0,
        'max' : 300,
        'logx' : False,
        'logy' : True,
    },     
    'ZW_MTWmme': {
        'title' : "MTW (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 500,
        'logx' : False,
        'logy' : True,
    },     
    'ZW_MTWmmeCSV': {
        'title' : "MTW (GeV)",
        'nbins' : 30,
        'min' : 0,
        'max' : 300,
        'logx' : False,
        'logy' : True,
    },            
    'ZW_MTWeem': {
        'title' : "MTW (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 500,
        'logx' : False,
        'logy' : True,
    },
    'ZW_MTWeemCSV': {
        'title' : "MTW (GeV)",
        'nbins' : 30,
        'min' : 0,
        'max' : 300,
        'logx' : False,
        'logy' : True,
    },         
    'ZW_MTWeee': {
        'title' : "MTW (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 500,
        'logx' : False,
        'logy' : True,
    },      
    'ZW_MTWeeeCSV': {
        'title' : "MTW (GeV)",
        'nbins' : 30,
        'min' : 0,
        'max' : 300,
        'logx' : False,
        'logy' : True,
    },         
    'ZW_Mmm3mu': {
        'title' : "M(mu+mu-) (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 300,
        'logx' : False,
        'logy' : True,
    },
    'ZW_Mmm2me': {
        'title' : "M(mu+mu-) (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 300,
        'logx' : False,
        'logy' : True,
    },
    'ZW_Mee2em': {
        'title' : "M(e+e-) (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 300,
        'logx' : False,
        'logy' : True,
    },
    'ZW_Mee3e': {
        'title' : "M(e+e-) (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 300,
        'logx' : False,
        'logy' : True,
    },    
    'ZW_Mmm3muCSV': {
        'title' : "M(mu+mu-) (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 300,
        'logx' : False,
        'logy' : True,
    },
    'ZW_Mmm2meCSV': {
        'title' : "M(mu+mu-) (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 300,
        'logx' : False,
        'logy' : True,
    },
    'ZW_Mee2emCSV': {
        'title' : "M(e+e-) (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 300,
        'logx' : False,
        'logy' : True,
    },
    'ZW_Mee3eCSV': {
        'title' : "M(e+e-) (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 300,
        'logx' : False,
        'logy' : True,
    },
    'ZW_Mll3leptCSV': {
        'title' : "M(ll) (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 300,
        'logx' : False,
        'logy' : True,
    },            
    'ZW_MET3mu': {
        'title' : "MET (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 500,
        'logx' : False,
        'logy' : True,
    },
    'ZW_MET2me': {
        'title' : "MET (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 500,
        'logx' : False,
        'logy' : True,
    },
    'ZW_MET2em': {
        'title' : "MET (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 500,
        'logx' : False,
        'logy' : True,
    },
    'ZW_MET3e': {
        'title' : "MET (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 500,
        'logx' : False,
        'logy' : True,
    },        
    'ZW_nj30': {
        'title' : "Njets",
        'nbins' : 20,
        'min' : 0,
        'max' : 20,
        'logx' : False,
        'logy' : False,
    },
    'ZW_nj30CSV': {
        'title' : "Njets",
        'nbins' : 20,
        'min' : 0,
        'max' : 20,
        'logx' : False,
        'logy' : False,
    },    
    'ZW_HT': {
        'title' : "HT",
        'nbins' : 40,
        'min' : 0,
        'max' : 2000.,
        'logx' : False,
        'logy' : False,	
    },
    'ZW_ptZ': {
        'title' : "ptZ",
        'nbins' : 40,
        'min' : 0,
        'max' : 1000.,
        'logx' : False,
        'logy' : False,	
    },    
    'ZW_HTCSV': {
        'title' : "HT",
        'nbins' : 40,
        'min' : 0,
        'max' : 2000.,
        'logx' : False,
        'logy' : False,	
    },	
    'ZW_ptZCSV': {
        'title' : "ptZ",
        'nbins' : 40,
        'min' : 0,
        'max' : 1000.,
        'logx' : False,
        'logy' : False,	 
    },    
    'ZW_CSV': {
        'title' : "CSV ",
        'nbins' : 50,
        'min' : 0,
        'max' : 1.,
        'logx' : False,
        'logy' : True,
    }, 
    'ZW_CSV2': {
        'title' : "CSV ",
        'nbins' : 50,
        'min' : 0,
        'max' : 1.,
        'logx' : False,
        'logy' : True,
    },         
    'mu3_maxMuIso': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,
    },    
    'mu3_HT': {
        'title' : "HT",
        'nbins' : 100,
        'min' : 0,
        'max' : 2000.,
        'logx' : False,
        'logy' : False,	
    },
    'mu3_mMin': {
        'title' : "Mmin",
        'nbins' : 100,
        'min' : 0,
        'max' : 200.,
        'logx' : False,
        'logy' : False,	
    },    
    'mu3_CSVmax': {
        'title' : "CSV",
        'nbins' : 50,
        'min' : 0.,
        'max' : 1.,
        'logx' : False,
        'logy' : False,	
    },
    'mu3_maxMuIsoCSVpt1525': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,
    },	
    'mu3_maxMuIsoCSVpt25': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,
    },	
    'mu3_maxMuIsoCSVpt40': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,
    },
    'Mue_isomu': {
        'title' : "isomu",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,
    },    	     
    'Mue_mass': {
        'title' : "m_{ll} (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 500,
        'logx' : False,
        'logy' : False,
    },
    'Mue_HT': {
        'title' : "HT (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 2000,
        'logx' : False,
        'logy' : False,
    },
    'Mue_nj30': {
        'title' : "Njets",
        'nbins' : 20,
        'min' : 0,
        'max' : 20,
        'logx' : False,
        'logy' : False,
    },
     'Mue_CSVmax': {
        'title' : "CSV",
        'nbins' : 50,
        'min' : 0,
        'max' : 1,
        'logx' : False,
        'logy' : False,
    },
    'e2mu_maxMuIso': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },          
    'e2mu_HT': {
        'title' : "HT",
        'nbins' : 100,
        'min' : 0,
        'max' : 2000.,
        'logx' : False,
        'logy' : False,	
    }, 
    'e2mu_mMin': {
        'title' : "Mmin",
        'nbins' : 100,
        'min' : 0,
        'max' : 200.,
        'logx' : False,
        'logy' : False,	
    },     
    'e2mu_CSVmax': {
        'title' : "CSV",
        'nbins' : 50,
        'min' : 0.,
        'max' : 1.,
        'logx' : False,
        'logy' : False,	
    },          
    'e2mu_maxMuIsoCSVpt1525': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },
    'e2mu_maxMuIsoCSVpt25': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },
    'e2mu_maxMuIsoCSVpt40': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },
    'lept3_maxMuIsoCSVpt1525': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,
    },	
    'lept3_maxMuIsoCSVpt25': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,
    },	
    'lept3_maxMuIsoCSVpt40': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,
    },       
    'SSmu_maxMuIso': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    }, 
    'SSmu_maxMuIsoIPlow': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    }, 
    'SSmu_nj30': {
        'title' : "HT",
        'nbins' : 20,
        'min' : 0,
        'max' : 20.,
        'logx' : False,
        'logy' : False,	
    },          
    'SSmu_HT': {
        'title' : "HT",
        'nbins' : 100,
        'min' : 0,
        'max' : 2000.,
        'logx' : False,
        'logy' : False,	
    }, 
    'SSmu_CSVmax': {
        'title' : "CSVmax",
        'nbins' : 50,
        'min' : 0,
        'max' : 1.,
        'logx' : False,
        'logy' : False,	
    },  
    'SSmu_CSVmaxLowIso': {
        'title' : "CSVmax",
        'nbins' : 20,
        'min' : 0,
        'max' : 1.,
        'logx' : False,
        'logy' : False,	
    },         
    'SSmu_maxMuIso2j': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    }, 
    'SSmu_maxMuIsoHT200': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },     
    'SSmu_maxMuIso2jPt1525': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    }, 
    'SSmu_maxMuIso2jPt2540': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    }, 
    'SSmu_maxMuIso2jPt25': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },   
    'SSmu_maxMuIso2jPt40': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },                        
    'SSmu_maxMuIso2jPt1525higIP': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    }, 
    'SSmu_maxMuIso2jPt2540higIP': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    }, 
    'SSmu_maxMuIso2jPt25higIP': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },   
    'SSmu_maxMuIso2jPt40higIP': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },  
    'SSmu_maxMuIso2jbveto': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },
   'SSmu_maxMuIsobvetoplus': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },
   'SSmu_maxMuIsobvetominus': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },         
    'SSmu_maxMuIso2jbvetoPt1525': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },
    'SSmu_Mjjbveto': {
        'title' : "Mjj (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 2500.,
        'logx' : False,
        'logy' : False,	
    },     
    'SSmu_Mjjbvetoplus': {
        'title' : "Mjj (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 2500.,
        'logx' : False,
        'logy' : False,	
    },
    'SSmu_Mjjbvetominus': {
        'title' : "Mjj (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 2500.,
        'logx' : False,
        'logy' : False,	
    },               
    'SSmu_maxMuIso2jbtag': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },
    'SSmu_maxMuIso2jbtagPt1525': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },     
    'SSmu_maxMuIso2jbtagPt40': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },
    'SSmu_maxMuIso2jbtagHT350': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },     
    'SSmu_HTbtagPt25': {
        'title' : "HT",
        'nbins' : 40,
        'min' : 0,
        'max' : 2000.,
        'logx' : False,
        'logy' : False,	
    },    
    'SSmue_maxMuIso': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    }, 
    'SSmue_maxMuIsoIPlow': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    }, 
    'SSmue_maxMuIsoTRGele': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },     
    'SSmue_nj30': {
        'title' : "HT",
        'nbins' : 20,
        'min' : 0,
        'max' : 20.,
        'logx' : False,
        'logy' : False,	
    },          
    'SSmue_HT': {
        'title' : "HT",
        'nbins' : 100,
        'min' : 0,
        'max' : 2000.,
        'logx' : False,
        'logy' : False,	
    }, 
    'SSmue_CSVmax': {
        'title' : "CSVmax",
        'nbins' : 50,
        'min' : 0,
        'max' : 1.,
        'logx' : False,
        'logy' : False,	
    },  
    'SSmue_CSVmaxLowIso': {
        'title' : "CSVmax",
        'nbins' : 20,
        'min' : 0,
        'max' : 1.,
        'logx' : False,
        'logy' : False,	
    },         
    'SSmue_maxMuIso2j': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    }, 
    'SSmue_maxMuIsoHT200': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },     
    'SSmue_maxMuIso2jPt1525': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    }, 
    'SSmue_maxMuIso2jPt2540': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    }, 
    'SSmue_maxMuIso2jPt25': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },   
    'SSmue_maxMuIso2jPt40': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },                        
    'SSmue_maxMuIso2jbveto': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },
   'SSmue_maxMuIsobvetoplus': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },
   'SSmue_maxMuIsobvetominus': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },         
    'SSmue_maxMuIso2jbvetoPt1525': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },
    'SSmue_Mjjbveto': {
        'title' : "Mjj (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 2500.,
        'logx' : False,
        'logy' : False,	
    },     
    'SSmue_Mjjbvetoplus': {
        'title' : "Mjj (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 2500.,
        'logx' : False,
        'logy' : False,	
    },
    'SSmue_Mjjbvetominus': {
        'title' : "Mjj (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 2500.,
        'logx' : False,
        'logy' : False,	
    },               
    'SSmue_maxMuIso2jbtag': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },
    'SSmue_maxMuIso2jbtagPt1525': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },     
    'SSmue_maxMuIso2jbtagPt40': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },
    'SSmue_maxMuIso2jbtagHT350': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0,
        'max' : 2.5,
        'logx' : False,
        'logy' : False,	
    },    
    'SSmue_HTbtagPt25': {
        'title' : "HT",
        'nbins' : 40,
        'min' : 0,
        'max' : 2000.,
        'logx' : False,
        'logy' : False,	
    },     
    'tt_Wqqmass': {
        'title' : "Mjj (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 1000,
        'logx' : False,
        'logy' : False,
    },  
    'tt_Tlvb1': {
        'title' : "Mlvb1 (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 1000,
        'logx' : False,
        'logy' : False,
    },  
    'tt_Tlvb2': {
        'title' : "Mlvb2 (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 1000,
        'logx' : False,
        'logy' : False,
    },  
    'tt_Tqqb1': {
        'title' : "Mqqb1 (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 1000,
        'logx' : False,
        'logy' : False,
    },  
    'tt_Tqqb2': {
        'title' : "Mqqb2 (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 1000,
        'logx' : False,
        'logy' : False,
    },                   
    'tte_Wqqmass': {
        'title' : "Mjj (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 1000,
        'logx' : False,
        'logy' : False,
    },  
    'tte_Tlvb1': {
        'title' : "Mlvb1 (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 1000,
        'logx' : False,
        'logy' : False,
    },  
    'tte_Tlvb2': {
        'title' : "Mlvb2 (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 1000,
        'logx' : False,
        'logy' : False,
    },  
    'tte_Tqqb1': {
        'title' : "Mqqb1 (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 1000,
        'logx' : False,
        'logy' : False,
    },  
    'tte_Tqqb2': {
        'title' : "Mqqb2 (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 1000,
        'logx' : False,
        'logy' : False,
    },                        
    'W_mass': {
        'title' : "m_{l#nu} (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 200,
        'logx' : False,
        'logy' : False,
    },
    'W_tmass': {
        'title' : "m_{T} (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 200,
        'logx' : False,
        'logy' : False,
    },
    'W_pt': {
        'title' : "p_{T}^{l#nu} (GeV)",
        'nbins' : 50,
        'min' : 0,
        'max' : 1000,
        'logx' : False,
        'logy' : True,
    },
    'minMuonIso': {
        'title' : "minimum Muon Iso",
        'nbins' : 100,
        'min' : 0.01,
        'max' : 5.01,
        'logx' : True,
        'logy' : False,
    },
    'maxMuonIso': {
        'title' : "maximum Muon Iso",
        'nbins' : 100,
        'min' : 0.01,
        'max' : 5.01,
        'logx' : True,
        'logy' : False,
    },
    'lumiWeight': {
        'title' : "lumiWeight",
        'nbins' : 1000,
        'min' : 0.,
        'max' : 1.5,
        'logx' : False,
        'logy' : True,
    },
}

